# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Unnamed Reverse Engineering Podcast'
tagline:          ''
description:      'Unnamed Reverse Engineering Podcast'
url:              http://unnamedre.github.io

author:
  name:           'Alvaro Prieto and Jen Costillo'
  url:            https://twitter.com/unnamed_show

paginate:         5
